### ISSUE TITLE
DataFrames/Tables.jl support as inputs

### ISSUE THREAD

**Issue by oxinabox** [invenia/ObservationDims.jl#14]
Often one wants to convert an DataFrame/Table into Matrix.

DataFrames are naturally observation per row.
For a `AbstractDataFrame`  I think `Matrix(df)` makes it into a `Matrix`.
I am not sure if there is a generalization of this to all Tables?

**Comment by iamed2** [comment]
Since Tables is trait-based and cannot dispatch, this functionality is implemented as [`Tables.matrix(table)`](https://juliadata.github.io/Tables.jl/stable/#Tables.matrix)
