### ISSUE TITLE
Generalise to higher-dimensional observations

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/ObservationDims.jl#6]
right now we only support 0-d observations (scalars-like) and 1-d observations (vector-like), but we should generalise this to 3-d (matrix-like) and so on

e.g. some may store `Matrix` observations not as a `Vector{<:Matrix{T}}` but as an `Array{T, 3}`

**Comment by oxinabox** [comment]
I don't undertand this.
The content of observations is always: All dimensions other than the obs dimension.
So if you have a 4D array and you break it up on the obsdim you should have 3D observations.

If one some how has two dimensions that represent the observation.
then the easy thing to do is to use `reshape` to combine them i think?
Seems obscure enough to not be a problem for us to deal with right now
